                                                                                     
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 
 */
public class sender extends javax.swing.JFrame {

    /**
     * Creates new form sender
     */
    public sender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        index = new javax.swing.JTextField();
        add = new javax.swing.JRadioButton();
        min = new javax.swing.JRadioButton();
        generate = new javax.swing.JButton();
        enc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rec = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENCRYPTION");
        setMinimumSize(new java.awt.Dimension(480, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Original Text:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 90, 30);
        getContentPane().add(msg);
        msg.setBounds(130, 70, 249, 55);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Change By:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 104, 17);
        getContentPane().add(index);
        index.setBounds(220, 160, 53, 35);

        add.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(add);
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 153, 0));
        add.setText("+");
        getContentPane().add(add);
        add.setBounds(140, 150, 41, 31);

        min.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(min);
        min.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        min.setForeground(new java.awt.Color(255, 153, 0));
        min.setText("-");
        getContentPane().add(min);
        min.setBounds(140, 190, 33, 31);

        generate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate.setForeground(new java.awt.Color(51, 0, 102));
        generate.setText("Generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate);
        generate.setBounds(310, 160, 120, 30);
        getContentPane().add(enc);
        enc.setBounds(131, 234, 251, 54);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Encrypted");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 234, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Send To");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(27, 306, 100, 17);
        getContentPane().add(rec);
        rec.setBounds(131, 306, 170, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 102));
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(321, 306, 90, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 370, 120, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-6, -16, 520, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int b; 
    
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        //String recv=rec.getText();
        String a = msg.getText();
         b = Integer.parseInt(index.getText());
      String encrypted="";
        if(min.isSelected()){
            for(int i=0;i<a.length();i++){
                if(a.charAt(i)==' ') encrypted+=" ";
                else{
                    char c = a.charAt(i);
                    double d = (double)(c);
                    char t = (char)(d-b);
                    encrypted+=t;
                }
            }
            enc.setText(encrypted);
        }
        else if(add.isSelected()){
            for(int i=0;i<a.length();i++){
                if(a.charAt(i)==' ') encrypted+=" ";
                else{
                    char c = a.charAt(i);
                    double d = (double)(c);
                    char t = (char)(d+b);
                    encrypted+=t;
                }
            }
            enc.setText(encrypted);
                
        }
       
            
 
    }//GEN-LAST:event_generateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            String recv = rec.getText();
            String msge = enc.getText();
            String sender =  new login().a;
            b = Integer.parseInt(index.getText());
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/12b","root","1234");
            Statement s = c.createStatement();
            
            System.out.println("insert into "+recv+" values('"+sender+"', '"+msge+"',"+b+");");
            s.execute("insert into "+recv+" values('"+sender+"', '"+msge+"',"+b+");");
            JOptionPane.showMessageDialog(rootPane,"Message sent");
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Something went wrong, maybe wrong name of reciever");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 login obj= new login();
 obj.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField enc;
    private javax.swing.JButton generate;
    private javax.swing.JTextField index;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton min;
    private javax.swing.JTextField msg;
    private javax.swing.JTextField rec;
    // End of variables declaration//GEN-END:variables
}
